name: MATLAB DEV CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]
env:
  MATHWORKS_SKIP_ACTIVATION: true
  MATHWORKS_ACCOUNT: ${{ secrets.MATHWORKS_ACCOUNT }}
  MATHWORKS_TOKEN: ${{ secrets.MATHWORKS_TOKEN }}

jobs:
  test-and-build:
    runs-on: shellai-runner-private-tst
    steps:
      - uses: actions/checkout@v2
      
      - run: |
            curl https://packages.microsoft.com/keys/microsoft.asc | sudo apt-key add -
            curl https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/prod.list | sudo tee /etc/apt/sources.list.d/mssql-release.list
            sudo apt-get update
            sudo ACCEPT_EULA=Y apt-get install -y msodbcsql18
        name: Add ODBC Drivers for SQL Server
        
      - run: docker run -e "ACCEPT_EULA=Y" -e "SA_PASSWORD=TESTpassword1" -p 1433:1433 --name testSQL -d mcr.microsoft.com/mssql/server:2019-latest
        name : Setup MS SQL

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1.2.0
        with:
            release: R2021a

      - run: docker exec testSQL /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P TESTpassword1 -Q "CREATE DATABASE testSQL"
        name: Create Database
                
      - name: Run MATLAB Tests
        uses: matlab-actions/run-tests@v1.3.0
        with:
            test-results-junit: test-results/results.xml
            code-coverage-cobertura: code-coverage/coverage.xml
        env:
           SQL_DB_USER: sa
           SQL_DB_PWD: TESTpassword1
           SQL_DB_SERVER: localhost
           SQL_DB_DATABASE: testSQL
           CURRENT_ENVIRONMENT: dev
            
      - name: Build for MPS
        uses: matlab-actions/run-command@v1.1.0
        if: ${{ github.ref == 'refs/heads/develop' }}
        with:
            command: compile
        env:
           SQL_DB_USER: ${{ secrets.TEST_DB_USER }}
           SQL_DB_PWD: ${{ secrets.TEST_DB_PWD }}
           SQL_DB_SERVER: ${{ secrets.TEST_DB_SERVER }}
           SQL_DB_DATABASE: ${{ secrets.TEST_DB_DATABASE }}
           BASIC_AUTH_USER: ${{ secrets.TEST_AUTH_USER }}
           BASIC_AUTH_PWD: ${{ secrets.TEST_AUTH_PWD }}
           CURRENT_ENVIRONMENT: dev
