name: MATLAB DEV CI

on:
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

jobs:
  test-and-build:
    runs-on: shellai-runner-private-tst
    steps:
      - uses: actions/checkout@v2

      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v1.2.0
                
      - name: Run MATLAB Tests
        uses: matlab-actions/run-tests@v1.3.0
            
      - name: Build for MPS
        uses: matlab-actions/run-command@v1.1.0
